title: My Coding Diaries
author: Shradha Rao
email: shradharaoworks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn Angular with me!. Blog posts for all Angular related.

theme: minima
# social links
github_username:  ShradhaCodes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
